connection: &connection
  adapter:  postgresql
  encoding: unicode
  host:     localhost
  pool:     5
  username: sharing_usr
  password: XwjBHA6NtrvDmL9Z

development:
  <<: *connection
  database: sharing_development

test: &test
  <<: *connection
  database: sharing_test
